### ISSUE TITLE
[Bug] Download of PDF Files concats ".pdf" in any case

### ISSUE THREAD

**Issue by cereal** [bevuta/pepa#3]
".pdf" is appended to the filename of a download (see: https://github.com/bevuta/pepa/blob/master/src/pepa/web/handlers.clj#L124)

a.pdf -> a.pdf.pdf

**Comment by the-kenny** [comment]
Moving this to our internal bug tracker for now. I'm not sure yet if we should fix this: A general, easy behavior is easier to reason about than special cases like not attaching .pdf in some cases.
