### ISSUE TITLE
Dockerized version

### ISSUE THREAD

**Issue by bbsbb** [bevuta/pepa#4]
Hey guys,

Would you consider adding a docker image version of Pepa (could be in a separate repository if you don't believe it's within scope). Alternatively, I can pull on this if you are open to the idea, but don't have the time to setup.

**Comment by the-kenny** [comment]
Hey!

Sorry for taking a few days to respond. We will try to supply a recipe for a docker image in the next days. Please note that this will be for trying it, not for production use (as we don't have db migrations yet).

Cheers,
Moritz

**Comment by bbsbb** [comment]
Great to hear! Easily trying out the application is exactly what I had in mind, so "not ready for production" is perfectly fine.

**Comment by DerGuteMoritz** [comment]
Hi @bbsbb, sorry for taking a bit longer but now it's finally there, see https://github.com/bevuta/pepa/tree/master/docker -- To make up for the wait, we also threw in `docker-compose` which should give you a fully working setup with a single commnad :smiley:
