### ISSUE TITLE
Can arbitrary network locations be mapped for import?

### ISSUE THREAD

**Issue by mattbk** [bevuta/pepa#9]
I'm interested in using pepa, but this feature would be necessary. Specifically, I'm looking for a tagging/search interface that will watch folders, leave the files where they are, and allow tagging and searching. Am I right to be looking at pepa, or should I look elsewhere. Thanks.

**Comment by the-kenny** [comment]
Sorry for the late answer. Pepa follows the strategy to import files into its database for archiving. It doesn't store references to files, but will copy the files verbatim (and of course will never modify the original data - neither in the filesystem nor in its database).

That said, we don't plan network share location import the way you suggest it. Of course you can simply upload all files from a given directory into Pepa, and we may write a client that will do so automatically in the future.
